# .error. Cannot yield a value in the body of a try block with a catch clause & Cannot yield a value in the body of a catch clause & Cannot yield in the body of a finally clause

class Test

	def main is shared
		pass
		
	def foo as IEnumerable<of int>
		try
			yield 1
		catch
			pass

	def bar as IEnumerable<of int>
		try
			pass
		catch
			yield 1
	
	def baz as IEnumerable<of int>
		try
			pass
		finally
			yield 2
