# used to cause an uncaught exception in the compiler

class Test

	def main
		d = {'x': 1}
		for key in d.keys.badName, pass  # .error. cannot find
