class Test

	def main is shared

		x as int

		try
			x = 3
			if x==1
				print 1
			else if x==2
				print 2
			else
				throw FallThroughException(x)
		catch fte as FallThroughException
			assert fte.info==3
