# Note that the `passthrough` type is used in error recover. `obj.badName` for example will be given the passthrough type so that compilation can proceed without creating extraneous errors
class Program

	def main is shared
		x = 2
		y = 2
		assert x + (y to passthrough) == 4
		assert (x to passthrough) + y == 4
		assert (x to passthrough) + (y to passthrough) == 4
