# .error. throw an exception

class Test
	def main is shared
		raise Exception('message')
